Reformat

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -3,37 +3,18 @@
 # Assign user
 export USER="build"
 
-# Set default environment variables
-DEVICE_LIST=
-JACK_RAM="4G"
-export USE_CCACHE=1
-CCACHE_SIZE="75G"
-TAG=14.1
-TYPE="WEEKLY"
-SIGN_BUILDS=0
-NAME=
-EMAIL=
+if [ -z "$DEVICE_LIST" ]; then
+    echo "Error: No device specified"
+    exit 1
+fi
 
-while [[ $# > 0 ]]; do
-    key="$1"
-    case $key in
-        --device-list) DEVICE_LIST=$2 ;;
-        --jack-ram) JACK_RAM=$2 ;;
-        --no-ccache) export USE_CCACHE=0 ;;
-        --ccache-size) CCACHE_SIZE=$2 ;;
-        -t|--tag) TAG=$2 ;;
-        --type) TYPE=$2 ;;
-        --sign-builds) SIGN_BUILDS=1 ;;
-        --migration) TYPE="MIGRATION" && SIGN_BUILDS=1 ;;
-        --name) NAME=$2 ;;
-        --email) EMAIL=$2 ;;
-    esac
-    shift
-done
+if [ -z "$NAME" ] || [ -z "$EMAIL" ]; then
+    echo "Warn: Name/Email not provided"
+else
+    git config --global user.name $NAME
+    git config --global user.email $EMAIL
+fi
 
-# Set Name and Email
-git config --global user.email $EMAIL
-git config --global user.name $NAME
 # Allocate RAM to jack
 export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx$JACK_RAM"
 
